package client.net.sf.saxon.ce.event

//remove if not needed
import scala.collection.JavaConversions._

object ReceiverOptions {

  /**
   * Flag indicating that duplicate namespace prefixes should be rejected
   */
  val REJECT_DUPLICATES = 32

  /**
   * Flag indicating that the namespace (of an element or attribute name)
   * has already been declared; it does not need to be generated by the namespace
   * fixup process.
   */
  val NAMESPACE_OK = 64

  /**
   * Flag passed on startElement indicating that the element does not inherit
   * the namespaces of its ancestors.
   */
  val DISINHERIT_NAMESPACES = 128

  /**
   * Flag set on startDocument() in relation to an xsl:message call with terminate="yes"
   */
  val TERMINATE = 16384
}
