// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
// This Source Code Form is “Incompatible With Secondary Licenses”, as defined by the Mozilla Public License, v. 2.0.
package org.orbeon.darius.xpath.event

object ReceiverOptions {

  /**
   * Flag indicating that duplicate namespace prefixes should be rejected
   */
  val REJECT_DUPLICATES = 32

  /**
   * Flag indicating that the namespace (of an element or attribute name)
   * has already been declared; it does not need to be generated by the namespace
   * fixup process.
   */
  val NAMESPACE_OK = 64

  /**
   * Flag passed on startElement indicating that the element does not inherit
   * the namespaces of its ancestors.
   */
  val DISINHERIT_NAMESPACES = 128

  /**
   * Flag set on startDocument() in relation to an xsl:message call with terminate="yes"
   */
  val TERMINATE = 16384
}
